services:
  postgres:
    image: postgres:15-alpine
    container_name: bookshelf-postgres
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      PGPORT: ${DATABASE_PORT}
    ports:
      - "5434:5433"
    volumes:
      - bookshelf_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      dockerfile: docker/api.Dockerfile
    container_name: bookshelf-server
    image: bookshelf-server:latest
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy

  # etl-worker:
  #   build:
  #     dockerfile: docker/etl-worker.Dockerfile
  #   depends_on:
  #     - rabbitmq
  #
  # etl-batcher:
  #   build:
  #     dockerfile: docker/etl-worker.Dockerfile
  #   depends_on:
  #     - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management

volumes:
  bookshelf_data:
